### ISSUE TITLE
Não salva na rule zero a esquerda

### ISSUE THREAD

**Issue by JoaoVagner** [matheusgontijo/easy-shipping-rules#1]
Quando coloco um range de cep de 08000-05000 depois que salva, o campo remove os zero as esqueda, ficando como: 8000-5000

**Comment by matheusgontijo** [comment]
João, muito obrigado pela issue.

Isso se deve à estrutura de regras que o Magento provê. Não é algo relacionado ao módulo.

Porém, se analisarmos bem, os zeros à esquerda nada alteram no momento da maneira em que o módulo trabalha. Exemplos:

São Paulo:
01000001-05999999
08000000-08499999

São Paulo (sem zeros à esquerda):
1000001-5999999
8000000-8499999


São Paulo (com muuuuitos zeros à esquerda):
00000000001000001-00000000005999999
00000000008000000-00000000008499999
