### ISSUE TITLE
NÃO salva na Regra de zerar a Esquerda e impossibilita compra

### ISSUE THREAD

**Issue by TiagoNMachado** [matheusgontijo/easy-shipping-rules#10]
Bom dia Matheus, tudo bem?

Primeiramente quero agradecer pelo seu módulo, pois nos ajudou demais a construir nossas regras de CEP.
Porém, estamos enfrentando o mesmo problema de um post que vi em seu GitHub, no qual uma pessoa também fala sobre "Não salvar na rule zero a esquerda".

Você informou o mesmo que não havia problema pois a contagem do cep é a mesma. Mas vários clientes não estão conseguindo comprar em nossa loja pq após inserir os ceps que se iniciam com zero, ele não puxa a regra de frete gratis ou qualquer outra regra que criamos.

Estou usando o Checkout Transparente Venda Mais para finalização das compras.

Como posso solucionar esse problema? Já venho alguns dias tentando resolver e estou perdendo clientes por este motivo.

Minha loja virtual é https://www.cantinhodoovo.com.br

Fico no aguardo.

**Comment by matheusgontijo** [comment]
Thiago, todo zero a esquerda é irrelevante. 000010 ou 10, são a mesma coisa.
Obrigado.
