### ISSUE TITLE
O módulo não mostra resultados se o cliente não estiver logado?

### ISSUE THREAD

**Issue by Tellys** [matheusgontijo/easy-shipping-rules#13]
Bom dia!

Primeiramente parabéns pelo projeto, excelente!!

Fiz alguns testes com o módulo, funciona muito bem! Contudo, so aparecem os resultados das regras para clientes logados, vc teria alguma dica para poder exibir os resultados das regras ao cliente não logado?

Grande abraço
TFA
TEllys

**Comment by matheusgontijo** [comment]
Tellys,

As regras podem ser criadas para todos os tipos de grupos de clientes, dentre eles logados e não logados.

O que deve estar acontecendo é que você está criando as regras baseadas APENAS em grupos logados. Portanto, marque a opção para "NÃO LOGADOS"... ou "Not logged in".

Matheus Gontijo.

**Comment by Tellys** [comment]
Fala Matheus, mto obrigado pelo retorno. Deu certinho aqui. 

Show o projeto seu, parabéns. 

Sou programar, PHP é minha paixão, contudo ainda não tive muito tempo para desvendar a rotina de desenvolvimento do Magento, vc poderia me indicar alguma literatura ou site que tenha algum tutorial para iniciantes em Magento.

Em projetos como o seu , seria uma honra colaborar.

Abraço
TFA

**Comment by matheusgontijo** [comment]
https://github.com/benmarks/magento-resources

Abraço!

**Comment by kimtiago** [comment]
estou com o mesmo problema, usuarios não logados não aparece o frete. como fez pra resolver isso?

**Comment by matheusgontijo** [comment]
@kimtiago da uma olhadinha na resposta acima, deve ser o mesmo problema. Valeu!

**Comment by kimtiago** [comment]
mas aonde faço isso? nas regras não aparece.

![screen shot 01-19-17 at 08 09 pm](https://cloud.githubusercontent.com/assets/11681263/22130567/36001cfe-de83-11e6-84e3-4b5e53559d9b.PNG)

**Comment by matheusgontijo** [comment]
CASO o usuário esteja deslogado sua regra provavelmente não irá funcionar (de acordo com a imagem acima), pois já que o usuário não é está logado significa que ele não faz parte de NENHUM GRUPO, e sua regra apenas permite o grupo GERAL.

Bem, é bem provavel que seja a configuração... Vai tentando adicionar regra-por-regra...

Comece somente por "quando o subtotal for igual ou maior que $1", então teste e veja se funciona. Se sim, continue adicionando regra por regra até ver onde quebra.

**Comment by kimtiago** [comment]
não estou usando nenhuma regra para usuário. mostrei acima só para perguntar se era ali que eu selecionava os não logados. minha regra está assim

![screen shot 01-19-17 at 08 21 pm](https://cloud.githubusercontent.com/assets/11681263/22130786/ed106a56-de84-11e6-81c1-5700123ebcdc.PNG)

**Comment by matheusgontijo** [comment]
1) Você está usando o Onestep Checkout ou a versão normal do checkout do Magento?
2) Você tentou adicionar APENAS A REGRA "quando o subtotal for igual ou maior que $1"?

**Comment by kimtiago** [comment]
já tentei até sem regra nenhuma.
uso o OneStepCheckout6 do Deivison.

**Comment by kimtiago** [comment]
desculpa tomar seu tempo mano... estou na correria pra migrar uma loja e esqueci desse detalhe básico. somente depois de entrar com o cep no cadastro é que ele vai listar as formas de envio.

**Comment by matheusgontijo** [comment]
Sorry, o módulo não suporta o OSC ainda. Esse é o motivo.
