### ISSUE TITLE
How to make Shipping Rules Show in Admin Order?

### ISSUE THREAD

**Issue by nflint** [matheusgontijo/easy-shipping-rules#14]
Matheus, 

Great Module! I am wondering if you have an idea about how to make the shipping rules show in an Admin Order? Any help is greatly appreciated.

**Comment by nflint** [comment]
I fixed it. The issue was present only in Magento configurations with multiple website. When a Custom Method was assigned to a given website the admin order screen was not displaying the custom method. The issue was the Collection.php was not able to get the website associated with a new order. See: https://github.com/flintdigital/mage-mod-easy-shipping-rules-fd/commit/325e391ae41dec69d0c19f7641308cb67a2d7173  
Let me know if you want to pull this. Also we would be interested in porting this to Magento 2.0 if anyone is interested in helping with that.

**Comment by matheusgontijo** [comment]
So cool @nflint! You just awesome!
YEAH, let's porting this to M2!
