### ISSUE TITLE
Nenhum metodo

### ISSUE THREAD

**Issue by kimtiago** [matheusgontijo/easy-shipping-rules#15]
Olá,

Estou tento um problema com o módulo e o OSC6. Se alguma chamada ajax é feita na página de checkout (por exemplo digitar o CEP para buscar o endereço), ele perde a seleção do frete e diz "Informe uma forma de entrega" ao clicar em finalizar pedido. Mas já está selecionado e como só tem 1, não tenho como clicar em outro pra refazer a seleção.

![screen shot 01-27-17 at 11 39 am](https://cloud.githubusercontent.com/assets/11681263/22376768/b3f8b2da-e485-11e6-855e-3e73ab6c7bd8.PNG)

**Comment by matheusgontijo** [comment]
Sorry, o módulo não dá suporte para OSC6.
