### ISSUE TITLE
Sobre Custom Methods, Rulez e outra coisas

### ISSUE THREAD

**Issue by JoaoVagner** [matheusgontijo/easy-shipping-rules#2]
Um tópico para levantar alguns tópicos a serem explicados em uma documentação inicial, sugiro:

# Instalação

## Arquivos e pastas

# O que é:
* Carriers
* Custom Methods
* Existing Methods
* Rules 

# Tradução

# Créditos

**Comment by matheusgontijo** [comment]
Grato pela colaboração bem como o cuidado, João.

Todos os pontos citados virão através de um site (que será lançado ASAP) com toda documentação.

**Comment by matheusgontijo** [comment]
Olá, site criado com sucesso: http://www.easyshippingrules.com.
Aguardando teu feedback. Grato.
