### ISSUE TITLE
Error on Shiping rules in backend

### ISSUE THREAD

**Issue by mostmaz** [matheusgontijo/easy-shipping-rules#6]
running magento 1.9 
could you please solve the problem because i am really depending on it

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'margobox_porto.easyshippingrules_carrier' doesn't exist, query was: SELECT `main_table`.* FROM `easyshippingrules_carrier` AS `main_table`

Trace:
#0 /chroot/home/margobox/margobox.com/html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /chroot/home/margobox/margobox.com/html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /chroot/home/margobox/margobox.com/html/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /chroot/home/margobox/margobox.com/html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /chroot/home/margobox/margobox.com/html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /chroot/home/margobox/margobox.com/html/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /chroot/home/margobox/margobox.com/html/lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /chroot/home/margobox/margobox.com/html/lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /chroot/home/margobox/margobox.com/html/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /chroot/home/margobox/margobox.com/html/lib/Varien/Data/Collection.php(683): Varien_Data_Collection->getIterator()
#11 /chroot/home/margobox/margobox.com/html/app/code/community/MatheusGontijo/EasyShippingRules/Model/Resource/Carrier/Collection.php(33): Varien_Data_Collection->_toOptionArray('easyshippingrul...', 'name')
#12 /chroot/home/margobox/margobox.com/html/app/code/community/MatheusGontijo/EasyShippingRules/Block/Adminhtml/Easyshippingrules/Existingmethod/Grid.php(158): MatheusGontijo_EasyShippingRules_Model_Resource_Carrier_Collection->toOptionArray()
#13 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(571): MatheusGontijo_EasyShippingRules_Block_Adminhtml_Easyshippingrules_Existingmethod_Grid->_prepareMassaction()
#14 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(625): Mage_Adminhtml_Block_Widget_Grid->_prepareMassactionBlock()
#15 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#16 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#17 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#18 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#19 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#20 /chroot/home/margobox/margobox.com/html/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#21 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/ma...')
#22 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#23 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#24 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#25 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#26 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#27 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#28 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#29 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#30 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#31 /chroot/home/margobox/margobox.com/html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#32 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(241): include('/chroot/home/ma...')
#33 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#34 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#35 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#36 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#37 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#38 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#39 /chroot/home/margobox/margobox.com/html/app/code/community/MatheusGontijo/EasyShippingRules/controllers/Adminhtml/Easyshippingrules/ExistingmethodController.php(47): Mage_Core_Controller_Varien_Action->renderLayout()
#40 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): MatheusGontijo_EasyShippingRules_Adminhtml_Easyshippingrules_ExistingmethodController->indexAction()
#41 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#42 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#43 /chroot/home/margobox/margobox.com/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#44 /chroot/home/margobox/margobox.com/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#45 /chroot/home/margobox/margobox.com/html/index.php(87): Mage::run('', 'store')
#46 {main}

**Comment by matheusgontijo** [comment]
Dear, it sounds an error about not correct installation. Probably those files didn't run correctly.

- You may clean cache in admin and make sure everything was instaled correctly

OR

- Try to reinstall, running this SQL command (be careful, test it in development):

```
DELETE FROM `__DATABASE_NAME__`.`core_resource` WHERE `core_resource`.`code` = 'easyshippingrules_setup'
```

**Comment by mostmaz** [comment]
thank you for quick response
i figured out the probleme 
i didnot install the package correctly.
could you please offer me the package.xml or the whole package that could be installed through magento connect?

**Comment by matheusgontijo** [comment]
I didn't published in Magento Connect yet, BUT, you may download the whole thing here: https://github.com/matheusgontijo/easy-shipping-rules/archive/master.zip

**Comment by mostmaz** [comment]
i did dowload it and extract it to the main root folder of magento and it appeared at the back end but the installation is missing some files like the database which i am sure is not installed in phpmyadmin

**Comment by mostmaz** [comment]
as you know there is Direct package file upload in magento connect manager that doesnt need magento connect key just you need to upload the package and press Upload, but the master.zip doesnt contain package.xml so it fails 
refer to this link please: http://info.magento.com/rs/magentocommerce/images/packagingmagentoconnectextensions6%200.pdf
