### ISSUE TITLE
Shipping method don`t displayed

### ISSUE THREAD

**Issue by danielchicote** [matheusgontijo/easy-shipping-rules#9]
Hello thanks for this great piece of code, looks very usefull. I have the module installed and working, but results that my most important method of shipping is not displayed in the "Carriers and Shipping Methods" list, and i don´t know how to solve it.

Can someone tell me something? Thanks!!
![izzpxm5](https://cloud.githubusercontent.com/assets/7643167/11048758/0d6e6a3a-873a-11e5-8f4f-36a8f7251e29.png)

**Comment by matheusgontijo** [comment]
It lists every single shipping method.

Is the wanted method showing successfully in the Magento Config "Shipping"?

If so, please, send the screen shoot.

**Comment by danielchicote** [comment]
Yes, my shipping method is activated and is working. Also, the easy shipping rules work correctly the module. But i cannot select this method on the list, only i can use it when is selected the "All shipping Methods" option. I supponse that is an error, conflict or uncompatibility of my shipping module.

But and can't see errors in the logs, or the module conflict detector.

**Comment by matheusgontijo** [comment]
Well, the only way we could solve it is adding your shipping module and debugging it. Would want to send me? If so, I can help you. Regards.

matheus@matheusgontijo.com
